### ISSUE TITLE
All devices not connected

### ISSUE THREAD

**Issue by MC-1984** [DrozmotiX/ioBroker.wled#140]
**Describe the bug**  
All WLED Devices are not connected (red dots). Using the URL of the ESP works fine. So it is not in issue with the ESP or the LED stripe.

The log says:
`
wled.0 | 2021-03-06 14:46:35.747 | error | (19779) Cannot read property 'error' of undefined
-- | -- | -- | --
wled.0 | 2021-03-06 14:46:35.746 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
wled.0 | 2021-03-06 14:46:35.746 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:352:25)
wled.0 | 2021-03-06 14:46:35.746 | error | at process.exit (internal/process/per_thread.js:169:15)
wled.0 | 2021-03-06 14:46:35.746 | error | at process.emit (events.js:315:20)
wled.0 | 2021-03-06 14:46:35.746 | error | at Object.onceWrapper (events.js:422:26)
wled.0 | 2021-03-06 14:46:35.746 | error | at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8620:22)
wled.0 | 2021-03-06 14:46:35.746 | error | at Wled.emit (events.js:315:20)
wled.0 | 2021-03-06 14:46:35.746 | error | at Wled.onUnload (/opt/iobroker/node_modules/iobroker.wled/main.js:97:13)
wled.0 | 2021-03-06 14:46:35.746 | error | (19779) TypeError: Cannot read property 'error' of undefined
wled.0 | 2021-03-06 14:46:35.743 | error | (19779) unhandled promise rejection: Cannot read property 'error' of undefined
wled.0 | 2021-03-06 14:46:35.742 | error | (19779) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
wled.0 | 2021-03-06 14:46:35.216 | warn | (19779) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
wled.0 | 2021-03-06 14:46:35.211 | error | (19779) wled.0 already running
` 
**Versions:**  
 - Adapter version: 0.5.6
 - JS-Controller version: 3.2.16
 - Node version: 14.16.0
 - Operating system: debian stable

Edit: A restart of the RPI solved the error. I leave the issue open in case you want to have a look at what caused the error.

**Comment by captaindork** [comment]
Hi, 
I am actually experiencing the same. Around once a week i will find the adapter in this state. Sometimes a reboot fixes it and to me it feels like sometimes it is even caused by a reboot.
I am using the same iobroker and Adapter Versions, but Nodejs 12.21 instead, so its probably not related to Node14. Also for me only the Adapter stops working. http or the WLED IOS App work fine...

I am working with presets in the ESP, which run at bootup, so at least the LEDs do not lightup in the bright default orange scheme after some days, which is quite annoying.

i wanted to find some patterns which lead to this issue before raising it here, but for now i am not able to clearly reproduce... however ist happens very often for me...

So if i can test or send logs, let me know... i would be very happy if this could be fixed!

**Comment by DutchmanNL** [comment]
I assume, based on the info I get here, the ESP is rebooting or overloading its heap-memory de to all JSON-API calls.

I already had it on the to-do to change the whole connection logic fromm rest-api to web socket which will make it more efficient.
Will keep this issue open until the web socket is implemented, than testing will be required by you friends if that indeed will solve the problem

**Comment by DutchmanNL** [comment]
please try with 0.5.7 should be solved

**Comment by MC-1984** [comment]
Thank you! As the error only occur sporadically, I will reopen the issue if it happens again!
